### PR TITLE
Pass in component instance and add _reactInternalInstance to setValueForStyles call

### PR DESCRIPTION
**Pull request by browniefed**
Should fix issues with React `15.1.0`
#35

### CODE REVIEW

**Comment by browniefed** [comment]
@vjeux or @lelandrichardson could you review this?

**Comment by vjeux** [comment]
Unfortunate that we have to pass an underscore attribute but why not, sgtm

**Comment by browniefed** [comment]
Yeah I know :(, it's only for DEV mode and we are already reaching into core to grab the `CSSPropertyOperations`. Only needed because now debugger in React requires `_debugID` and that exists on the internal instance. Happy to change it, just didn't know what to change it to.

**Comment by loris** [comment]
+1

**Pull request merged**
