### PR TITLE
Update README example

### PR DESCRIPTION
**Pull request by 9jaswag**
based off of the feedback by @justim and @michalochman on [103](https://github.com/animatedjs/animated/pull/103), I decided to update the README with a better example from the interractive docs.

### CODE REVIEW

**Comment by 9jaswag** [comment]
@justim and @michalochman. Do check and confirm if the example here is better than the current one. Thanks

**Comment by justim** [comment]
Much better! :)

**Comment by browniefed** [comment]
Sorry I had updated the code before hand, if you go ahead and rebase happy to merge.

**Comment by 9jaswag** [comment]
@browniefed I'll rebase and update the PR

**Comment by 9jaswag** [comment]
@browniefed I have updated the PR.

**Pull request merged**
