### PR TITLE
Move all classes into separate files

### LINKED ISSUE #6: Splitting up files
I'm thinking about opening a PR moving each class in the `AnimatedImplementation` file into it's own file for better organization.

Any strong feelings against this?

### PR DESCRIPTION
**Pull request by lelandrichardson**
to: @vjeux 

Moves everything into separate files. Also added the preamble to every file while I was at it.

I've verified everything in the interactive docs still work, so seems solid.  Let me know if anything seems off.

Fixes #6

### CODE REVIEW

**Comment by vjeux** [comment]
So much better! Is flow still working?

**Comment by lelandrichardson** [comment]
yep!

**Comment by lelandrichardson** [comment]
@vjeux look good to merge, then?

**Comment by vjeux** [comment]
Yup

**Pull request merged**
